# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://sunjunee.github.io
date_format: "ordinal"
title: sun
subtitle: "孙俊的个人博客"
description: "孙俊的个人博客"
keywords: sun
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 孙俊
organization: 中国科学院大学
github_username: sunjunee
location: 北京
email: sunjunee@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: gitalk
comments_provider: gitalk
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: sunjunee
    repo: blog-comments
    clientID: d5d737a0f704d4eac5a3
    clientSecret: f47d9229e2684a5ed5c5aeb69841668baeaca12b
